Venue show
Jessica-Mach/concert-venues-review-app pull request #5
Opened 2021-06-23 21:45 UTC by SafraSchwarz

- Added a show page to view an individual venue
- Created review entity and added join table to venue
- broke out the seeder to account for seeding venues and then reviews
- created a react component to show reviews on the show page itself

2021-06-23 22:10 UTC, safang99 requested changes
Great work with a really big PR.  As of right now we could and should split this into two PR's.  One that was first focused on just getting the show page up with no care for `reviews`.  Then after that is up and running we could have a second PR that is creating reviews and displaying them on the show page.  Please feel free to always post the user story you have created in stand-up/stand-down notes so we will see the scope of what you are planning or just ask a question if you think something is too small/large in scope.

2021-06-23 22:10 UTC, safang99 commented on src/main/frontend/components/NavBar.js
> +// import EditVenue from "./EditVenue.js"
commented out import that can be removed

2021-06-23 22:10 UTC, safang99 commented on src/main/frontend/components/NavBar.js
> +        <Route exact path="/concert-venues/:id" component={VenueShow} />
Just double checking that this is removing the concert venue edit path?

2021-06-23 22:10 UTC, safang99 commented on src/main/frontend/components/VenueShow.js
> +      console.log(venueData);
console.log statement that can be removed

2021-06-23 22:10 UTC, safang99 commented on src/main/frontend/components/VenueTile.js
> +      </a>
We can use `Link` components instead of anchor tags to take full advantage of React

2021-06-23 22:10 UTC, safang99 commented on src/main/java/com/launchacademy/reviews/controllers/AdminController.java
> +////}
Why is this all commented out now?

2021-06-24 15:13 UTC, SafraSchwarz commented
Fixed the requested changes.

2021-06-24 15:49 UTC, SafraSchwarz commented
Made the changed and and click tested. Ready for a pr now.

2021-06-24 15:58 UTC, safang99 requested changes
Looks like of a few of the requested changes weren't addressed, so just make sure to go back through and double check

2021-06-24 15:58 UTC, safang99 commented on src/main/frontend/components/VenueShowTile.js
> +import React, { useEffect, useState } from "react";
Is this component missing code or was it created by mistake maybe?

2021-06-24 15:58 UTC, safang99 commented on src/main/frontend/components/VenueTile.js
> +      </a>
These still need to be updated to `<Link/>` components

2021-06-24 16:02 UTC, merged